import re

# Database of highly overused student projects and keywords
OVERUSED_TOPICS = [
    {
        "keywords": [r"attendance", r"face.*attendance", r"qr.*attendance", r"fingerprint.*attendance"],
        "name": "Attendance Management System",
        "innovation_score": 15,
        "commonness_score": 96,
        "trend_score": 25,
        "rationale": "Over 95% of college departments see QR, Biometric, or Face-recognition attendance systems every semester. It is extremely common. To stand out, consider integrating localized bluetooth triangulation, predictive class-cutting ML models, or blockchain-based tamper-proof records."
    },
    {
        "keywords": [r"to-do", r"todo", r"task manager", r"notes app"],
        "name": "To-Do List or Notes App",
        "innovation_score": 8,
        "commonness_score": 98,
        "trend_score": 15,
        "rationale": "This is a basic CRUD tutorial application. Using it for a major project provides almost zero academic or resume impact. To elevate this, pivot into automated AI task prioritization, smart calendar sync using NLP agent executors, or collaborative real-time team boards."
    },
    {
        "keywords": [r"library", r"book.*store", r"book.*management"],
        "name": "Library Management System",
        "innovation_score": 12,
        "commonness_score": 94,
        "trend_score": 20,
        "rationale": "A traditional database CRUD app. It is considered an entry-level database course homework rather than a final year project. Upgrade this concept by introducing AI book recommendation graphs, computer-vision shelf audits, or automatic digital DRM management."
    },
    {
        "keywords": [r"e-commerce", r"ecommerce", r"shopping", r"online.*store", r"clothing.*store"],
        "name": "E-Commerce / Shopping Platform",
        "innovation_score": 22,
        "commonness_score": 89,
        "trend_score": 45,
        "rationale": "While technically comprehensive, generic e-commerce templates are everywhere. To make this professional, implement real-time dynamic pricing based on competitors, visual search using deep learning, or virtual AR dress-up overlays."
    },
    {
        "keywords": [r"chat.*app", r"messenger", r"chat.*room"],
        "name": "Basic Chat Application",
        "innovation_score": 28,
        "commonness_score": 82,
        "trend_score": 55,
        "rationale": "Standard WebSocket tutorial project. It is highly common on student Github profiles. Enhance this by creating an encrypted multi-agent workspace with autonomous developer bots, automated audio meeting transcriptions, or language translation overlays."
    },
    {
        "keywords": [r"portfolio", r"personal.*website"],
        "name": "Personal Portfolio Page",
        "innovation_score": 10,
        "commonness_score": 92,
        "trend_score": 30,
        "rationale": "Every student creates a portfolio. It is not suitable as a capstone or major engineering project. Pivot this into a headless CMS builder, an automated portfolio landing page generator driven by resume parsing, or an interactive developer network."
    }
]

def scan_project_originality(title: str, problem_statement: str, base_originality: dict) -> dict:
    """
    Scans the project title and details against overused keywords.
    If match found, it adjusts the innovation and commonness scores and overrides the rationale.
    Otherwise, it preserves and returns the AI-generated scores.
    """
    combined_text = f"{title} {problem_statement}".lower()
    
    for topic in OVERUSED_TOPICS:
        for pattern in topic["keywords"]:
            if re.search(pattern, combined_text):
                # We have a hit! Override the scores and rationale for realism.
                return {
                    "innovation_score": topic["innovation_score"],
                    "commonness_score": topic["commonness_score"],
                    "trend_score": topic["trend_score"],
                    "rationale": topic["rationale"]
                }
                
    # No matches, the project is unique!
    # Ensure innovation is high, commonness is low if generated by AI
    innovation = base_originality.get("innovation_score", 85)
    commonness = base_originality.get("commonness_score", 20)
    trend = base_originality.get("trend_score", 90)
    rationale = base_originality.get("rationale", "This project is highly innovative and focuses on novel technical implementations, showing low commonness and high growth potential.")
    
    return {
        "innovation_score": innovation,
        "commonness_score": commonness,
        "trend_score": trend,
        "rationale": rationale
    }
