/** Technologies offered per target domain in the Forge AI Simulator */
export const DOMAIN_TECHNOLOGIES = {
  'Artificial Intelligence / ML': [
    'Python',
    'PyTorch',
    'TensorFlow',
    'Scikit-learn',
    'OpenCV',
    'Pandas',
    'NumPy',
    'Hugging Face',
    'LangChain',
    'FastAPI',
    'Jupyter',
    'MLflow',
    'ONNX',
    'CUDA',
    'Google Gemini API',
  ],
  'Full-Stack Web Development': [
    'React.js',
    'Next.js',
    'Vue.js',
    'Node.js',
    'Express.js',
    'Python',
    'FastAPI',
    'Django',
    'PostgreSQL',
    'MongoDB',
    'Supabase',
    'Tailwind CSS',
    'TypeScript',
    'REST APIs',
    'GraphQL',
    'Docker',
  ],
  'Mobile App Development': [
    'React Native',
    'Flutter',
    'Swift',
    'Kotlin',
    'Firebase',
    'Expo',
    'Android Studio',
    'Xcode',
    'SQLite',
    'REST APIs',
    'Push Notifications',
    'Redux',
    'Dart',
    'Figma',
  ],
  'BlockChain / Web3': [
    'Solidity',
    'Ethereum',
    'Hardhat',
    'Web3.js',
    'Ethers.js',
    'IPFS',
    'Polygon',
    'Smart Contracts',
    'MetaMask',
    'Rust',
    'Foundry',
    'The Graph',
    'OpenZeppelin',
    'Truffle',
  ],
  'Internet of Things (IoT)': [
    'Arduino',
    'Raspberry Pi',
    'ESP32',
    'MQTT',
    'Node-RED',
    'Python',
    'C++',
    'Bluetooth BLE',
    'Wi-Fi',
    'InfluxDB',
    'Grafana',
    'AWS IoT',
    'Edge ML',
    'Sensors',
  ],
  Cybersecurity: [
    'Python',
    'Wireshark',
    'Kali Linux',
    'Burp Suite',
    'Nmap',
    'Metasploit',
    'SIEM',
    'Splunk',
    'OWASP',
    'Penetration Testing',
    'Cryptography',
    'Firewall',
    'Docker',
    'Linux',
    'Network Security',
  ],
};

export const DOMAIN_OPTIONS = Object.keys(DOMAIN_TECHNOLOGIES);
